### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pbz134** [woodyhoko/cytoid-level-downloader#1]
Hello,

After executing the script, entering a page number and my account credentials, I get the following error with cytoid_downloader.py:

Traceback (most recent call last):
  File "D:\PythonTests\cytoid_downloader.py", line 10, in <module>
    cooky = dict([[x[:11],x[12:].split(';')[0]] if x[12]=='=' else [x[:15],x[16:].split(';')[0]] for x in cook_request.headers['Set-Cookie'].split(', ') if x[:11]=='cytoid:sess'])
  File "D:\Programme\Miniconda3\envs\cytoid\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'

**Comment by woodyhoko** [comment]
Hmm, seems like https://api.cytoid.io is down... Let me figure out another way later today. Thanks for noticing me!

**Comment by woodyhoko** [comment]
Seems like cytoid's developer tried to avoid any type of bot access..... After some investigation, they used cloudflare's turnstiles to check if it is real human accessing the login page or not. Please ping me again if they released any API or if any solution is found.

**Comment by woodyhoko** [comment]
Please look into my latest experiments if you are interested in attempting yourself! I will be closing this issue for now.

**Comment by woodyhoko** [comment]
update status.

**Comment by woodyhoko** [comment]
Update status.
